services:
  xss:
    build: ./cors-xss
    ports:
      - 8000:8000
    environment:
      API_CALLER_DOMAIN: http://localhost:3000
  api-caller:
    build: ./cors-api-caller
    ports:
      - 3000:3000
    environment:
      MY_DOMAIN: http://localhost:3000
      API_DOMAIN: http://localhost:5000
  api:
    build: ./cors-api
    ports:
      - 5000:5000
